### AWS S3 Server ###
cloud:
  aws:
    credentials:
      accessKey: ENC(TzCmCwaesRqnHHirDgtAp+a+17FxJYHi+49DrT3Nmf0=)
      secretKey: ENC(Bjnp+6ENwYlEXvEJLlbtAVT7Ughmgqom4s0UrrIkSt6CECABfAvtlpCBRVDtHDisg2xSMZAr2iM=)
    s3:
      bucket: ENC(gZjR8l6H+2vxJXwOJ6yopNx/ppiY8SlWQpBXVcKkIrA=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

### MariaDB Release Server ###
spring:
  datasource:
    url: ENC(VukHz4I/AyobpFhnp41mjfVBCl6X6VxOkrbHR6PHHwEtwkMw4xSpGtlc8GYg7y2Zhy4wcwuvTtGVjXD3Adkkxw==)
    username: ENC(bGF1QpKuFm1KQzPMGPD8NIvWdoQbbcbJ)
    password: ENC(DV0w5wcWRKlfVphaWi8Mb83xOx5rx5Gh)

### KakaoMap Api Key ###
kakao:
  map:
    apiKey: ENC(r38lxxHEgR2UgVViu+F5a9H8kDhNnX3VXmYE+wdQGi1G6glVcckg1u1kQGknmAGutPwRGYc/o5c=)