### AWS S3 Server ###
cloud:
  aws:
    credentials:
      accessKey: ENC(vjVwjIVagaHg3yLooyPGpcf9vxWAOU52stO28+U0l+k=)
      secretKey: ENC(6V04gKV8csUtx+ZgKYpUtHLkPrbz3sEJHaVbVsUSRiFD9BtJcrtClCSalzfR9F7nw85iS7hCxUk=)
    s3:
      bucket: ENC(MQyyPOcgHYBcYb4KGMXsPc3hqnZ5UVIhdzM7xOfBQIJq6L9ytcdfi4lS4AiprzN3)
    region:
      static: ap-northeast-2
    stack:
      auto: false

### MariaDB Release Server ###
spring:
  datasource:
    url: ENC(8RGjgKwqoWxPXWWtozKImfcNo5GMUnCIMYvONc61FsNmKNqlVEmHnXVsHIEQBl9Ld7a/RJUCrSHzp7QxRKD0ldDBJju/8s6c)
    username: ENC(IYZiiPFZ/d7XM0OxII/y5ZjgTPU7eKRJ)
    password: ENC(tCx5PtshhUwYLTDIrXuItttIEB671nLL)

### KakaoMap Api Key ###
kakao:
  map:
    apiKey: ENC(r38lxxHEgR2UgVViu+F5a9H8kDhNnX3VXmYE+wdQGi1G6glVcckg1u1kQGknmAGutPwRGYc/o5c=)